name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy on push to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Ensure Node.js version is 18.x or higher

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        env:
          NEXT_PUBLIC_CONVEX_URL: ${{ secrets.NEXT_PUBLIC_CONVEX_URL }}  # Use GitHub Secret for Convex URL
        run: npm run build  # Run the build process

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for pushing to gh-pages
          publish_branch: gh-pages  # Publish to the 'gh-pages' branch
          publish_dir: ./out  # Directory to deploy (this is the default output from `next export`)
