name: Build and Deploy

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Ensure Node.js version is >=18

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        env:
          NEXT_PUBLIC_CONVEX_URL: ${ secrets.NEXT_PUBLIC_CONVEX_URL }  # Include the Convex URL from secrets
        run: npm run build  # Build the Next.js app and export static files

      - name: Move build to root directory
        run: mv out/* ./  # Move the static files to the root directory

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Deploy static site to main"
          git push origin main
